FROM golang:1.24.4-bookworm AS builder

WORKDIR /usr/app

COPY go.sum go.mod ./
RUN go mod download

COPY . .

RUN go build -o main ./cmd/main.go

FROM debian:bookworm

WORKDIR /app

COPY --from=builder /usr/app/main .

RUN chmod +x ./main

CMD ["./main"]