version: '3'
services: 
  redis-server:
    image: 'redis'
  go-app:
    restart: 'always'
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:8081" 
    volumes:
      - .:/usr/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/app
    command: ["go", "test", "./..."]